//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Data.HelperClasses;
using Data.FactoryClasses;
using Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Location'.<br/><br/></summary>
	[Serializable]
	public partial class LocationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<TravelEntity> _travels;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static LocationEntityStaticMetaData _staticMetaData = new LocationEntityStaticMetaData();
		private static LocationRelations _relationsFactory = new LocationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Travels</summary>
			public static readonly string Travels = "Travels";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class LocationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public LocationEntityStaticMetaData()
			{
				SetEntityCoreInfo("LocationEntity", InheritanceHierarchyType.None, false, (int)Data.EntityType.LocationEntity, typeof(LocationEntity), typeof(LocationEntityFactory), false);
				AddNavigatorMetaData<LocationEntity, EntityCollection<TravelEntity>>("Travels", a => a._travels, (a, b) => a._travels = b, a => a.Travels, () => new LocationRelations().TravelEntityUsingLocationId, typeof(TravelEntity), (int)Data.EntityType.TravelEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static LocationEntity()
		{
		}

		/// <summary> CTor</summary>
		public LocationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public LocationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this LocationEntity</param>
		public LocationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Location which data should be fetched into this Location object</param>
		public LocationEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Location which data should be fetched into this Location object</param>
		/// <param name="validator">The custom validator object for this LocationEntity</param>
		public LocationEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected LocationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Travel' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTravels() { return CreateRelationInfoForNavigator("Travels"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this LocationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static LocationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Travel' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTravels { get { return _staticMetaData.GetPrefetchPathElement("Travels", CommonEntityBase.CreateEntityCollection<TravelEntity>()); } }

		/// <summary>The Address property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Address".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.Address, true); }
			set	{ SetValue((int)LocationFieldIndex.Address, value); }
		}

		/// <summary>The City property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."City".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String City
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.City, true); }
			set	{ SetValue((int)LocationFieldIndex.City, value); }
		}

		/// <summary>The Country property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Country".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Country
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.Country, true); }
			set	{ SetValue((int)LocationFieldIndex.Country, value); }
		}

		/// <summary>The Description property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 1000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.Description, true); }
			set	{ SetValue((int)LocationFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)LocationFieldIndex.Id, true); }
			set { SetValue((int)LocationFieldIndex.Id, value); }		}

		/// <summary>The Name property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.Name, true); }
			set	{ SetValue((int)LocationFieldIndex.Name, value); }
		}

		/// <summary>The State property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."State".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String State
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.State, true); }
			set	{ SetValue((int)LocationFieldIndex.State, value); }
		}

		/// <summary>The Zip property of the Entity Location<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Locations"."Zip".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Zip
		{
			get { return (System.String)GetValue((int)LocationFieldIndex.Zip, true); }
			set	{ SetValue((int)LocationFieldIndex.Zip, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'TravelEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(TravelEntity))]
		public virtual EntityCollection<TravelEntity> Travels { get { return GetOrCreateEntityCollection<TravelEntity, TravelEntityFactory>("Location", true, false, ref _travels); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Data
{
	public enum LocationFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>City. </summary>
		City,
		///<summary>Country. </summary>
		Country,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		///<summary>State. </summary>
		State,
		///<summary>Zip. </summary>
		Zip,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Location. </summary>
	public partial class LocationRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between LocationEntity and TravelEntity over the 1:n relation they have, using the relation between the fields: Location.Id - Travel.LocationId</summary>
		public virtual IEntityRelation TravelEntityUsingLocationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Travels", true, new[] { LocationFields.Id, TravelFields.LocationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticLocationRelations
	{
		internal static readonly IEntityRelation TravelEntityUsingLocationIdStatic = new LocationRelations().TravelEntityUsingLocationId;

		/// <summary>CTor</summary>
		static StaticLocationRelations() { }
	}
}
