//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	[Serializable]
	[DataContract]
	public partial class UserTravel
	{
		/// <summary>Gets or sets the FirstName field. Derived from Entity Model Field 'User.FirstName'</summary>
		[DataMember]
		public System.String FirstName { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'User.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the LastName field. Derived from Entity Model Field 'User.LastName'</summary>
		[DataMember]
		public System.String LastName { get; set; }
		/// <summary>Gets or sets the Password field. Derived from Entity Model Field 'User.Password'</summary>
		[DataMember]
		public System.String Password { get; set; }
		/// <summary>Gets or sets the Travels field. </summary>
		[DataMember]
		public List<UserTravelTypes.Travel> Travels { get; set; }
	}

	namespace UserTravelTypes
	{
		/// <summary> DTO class which is derived from the entity 'Travel (Travels)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Travel
		{
			/// <summary>Gets or sets the Location field. </summary>
			[DataMember]
			public TravelTypes.Location Location { get; set; }
		}

		namespace TravelTypes
		{
			/// <summary> DTO class which is derived from the entity 'Location (Travels.Location)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Location
			{
				/// <summary>Gets or sets the Country field. Derived from Entity Model Field 'Location.Country'</summary>
				[DataMember]
				public System.String Country { get; set; }
				/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Location.Id'</summary>
				[DataMember]
				public System.Int32 Id { get; set; }
				/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Location.Name'</summary>
				[DataMember]
				public System.String Name { get; set; }
			}
		}
	}

}




