//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Data.HelperClasses
{
	/// <summary>Field Creation Class for entity LocationEntity</summary>
	public partial class LocationFields
	{
		/// <summary>Creates a new LocationEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Address); }}
		/// <summary>Creates a new LocationEntity.City field instance</summary>
		public static EntityField2 City { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.City); }}
		/// <summary>Creates a new LocationEntity.Country field instance</summary>
		public static EntityField2 Country { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Country); }}
		/// <summary>Creates a new LocationEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Description); }}
		/// <summary>Creates a new LocationEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Id); }}
		/// <summary>Creates a new LocationEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Name); }}
		/// <summary>Creates a new LocationEntity.State field instance</summary>
		public static EntityField2 State { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.State); }}
		/// <summary>Creates a new LocationEntity.Zip field instance</summary>
		public static EntityField2 Zip { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LocationFieldIndex.Zip); }}
	}

	/// <summary>Field Creation Class for entity TravelEntity</summary>
	public partial class TravelFields
	{
		/// <summary>Creates a new TravelEntity.DepartureDate field instance</summary>
		public static EntityField2 DepartureDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TravelFieldIndex.DepartureDate); }}
		/// <summary>Creates a new TravelEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TravelFieldIndex.Id); }}
		/// <summary>Creates a new TravelEntity.LocationId field instance</summary>
		public static EntityField2 LocationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TravelFieldIndex.LocationId); }}
		/// <summary>Creates a new TravelEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TravelFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Email); }}
		/// <summary>Creates a new UserEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.FirstName); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastName); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
	}
	

}