//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Data.FactoryClasses;
using Data.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Data.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitLocationEntityInfo();
			InitTravelEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits LocationEntity's info objects</summary>
		private void InitLocationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LocationFieldIndex), "LocationEntity");
			this.AddElementFieldInfo("LocationEntity", "Address", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.Address, 255, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "City", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "Country", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.Country, 255, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "Description", typeof(System.String), false, false, false, true,  (int)LocationFieldIndex.Description, 1000, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)LocationFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("LocationEntity", "Name", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "State", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.State, 255, 0, 0);
			this.AddElementFieldInfo("LocationEntity", "Zip", typeof(System.String), false, false, false, false,  (int)LocationFieldIndex.Zip, 10, 0, 0);
		}

		/// <summary>Inits TravelEntity's info objects</summary>
		private void InitTravelEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TravelFieldIndex), "TravelEntity");
			this.AddElementFieldInfo("TravelEntity", "DepartureDate", typeof(System.DateTime), false, false, false, false,  (int)TravelFieldIndex.DepartureDate, 0, 0, 0);
			this.AddElementFieldInfo("TravelEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)TravelFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("TravelEntity", "LocationId", typeof(System.Int32), false, true, false, false,  (int)TravelFieldIndex.LocationId, 0, 0, 10);
			this.AddElementFieldInfo("TravelEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)TravelFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Email", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Email, 500, 0, 0);
			this.AddElementFieldInfo("UserEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.FirstName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "LastName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.LastName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Password", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Password, 255, 0, 0);
		}
	}
}