//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Data.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitLocationEntityMappings();
			InitTravelEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits LocationEntity's mappings</summary>
		private void InitLocationEntityMappings()
		{
			this.AddElementMapping("LocationEntity", @"postgres", @"public", "Locations", 8, 0);
			this.AddElementFieldMapping("LocationEntity", "Address", "Address", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("LocationEntity", "City", "City", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("LocationEntity", "Country", "Country", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("LocationEntity", "Description", "Description", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("LocationEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.Locations_Id_seq", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("LocationEntity", "Name", "Name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("LocationEntity", "State", "State", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("LocationEntity", "Zip", "Zip", false, "Varchar", 10, 0, 0, false, "", null, typeof(System.String), 7);
		}

		/// <summary>Inits TravelEntity's mappings</summary>
		private void InitTravelEntityMappings()
		{
			this.AddElementMapping("TravelEntity", @"postgres", @"public", "Travel", 4, 0);
			this.AddElementFieldMapping("TravelEntity", "DepartureDate", "DepartureDate", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("TravelEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.Travel_Id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("TravelEntity", "LocationId", "LocationId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("TravelEntity", "UserId", "UserId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"postgres", @"public", "User", 5, 0);
			this.AddElementFieldMapping("UserEntity", "Email", "Email", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("UserEntity", "FirstName", "FirstName", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.User_Id_seq", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("UserEntity", "LastName", "LastName", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "Password", "Password", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 4);
		}

	}
}
